### ISSUE TITLE
Create Swing Arm Subsystem

### ISSUE THREAD

**Issue by abrightwell** [wando-advanced-robotics/PowerUpRobot#11]
The swing arm subsystem consists of one motor to control a Dart Actuator.

Actuator Motor: Victor SPX - CAN Bus Id: 4
Potentiometer: TBD - Analog Channel: 1

Create the following methods:

- [x] up():void - controls the actuator motor to move the swing arm up.
- [x] down():void - controls the actuator motor to move the swing arm down.
- [x] stop():void - stops the actuator motor.
- [x] position():double - returns the current position of the swing arm based on the value provided by the potentiometer

**Comment by BearsAreAwsome** [comment]
Has been done for a while
