### ISSUE TITLE
Configure competition bot TalonSRX's

### ISSUE THREAD

**Issue by abrightwell** [wando-advanced-robotics/PowerUpRobot#5]
The competition bot Talon's need to have their firmware updated and their addresses set according to what has been set in the code.

- [x] Update firmware

- [x] Configure addresses

- [x] Physically label the Talons with address.

**Comment by BearsAreAwsome** [comment]
On Saturday, we did update firmware and configure the addresses, however we have yet to label them.

**Comment by BearsAreAwsome** [comment]
Talons were finally labeled
